private["_item"];
_item="";
if("dmpBottleFullDirty"call dmp_fnc_HasItem)then{_item="dmpBottleFullDirty"};
if("dmpCanteenDirty"call dmp_fnc_HasItem)then{_item="dmpCanteenDirty"};
if(_item=="")exitWith{systemChat"No dirty water"};
//closeDialog 0;
//player playMove _animIn;sleep 3;
player removeItem _item;
if(_item=="dmpBottleFullDirty")then{player addItem"dmpBottleEmpty"};
if(_item=="dmpCanteenDirty")then{player addItem"dmpCanteenEmpty"};
systemChat"Emptied dirty water";