private["_man"];
_man=_this select 0;
_dam=_this select 2;
if!(local _man)exitWith{};
if(isPlayer _man)exitWith{};
if(dmpKnockdownDebug)then{systemChat format["_man: %1    _dam: %2",_man,_dam]};
_man setSuppression 1;
if(_dam<dmpKnockdownThreshold)exitWith{};
if((!dmpKnockdownAffectPlayers)AND(isPlayer _man))exitWith{};
if((!dmpKnockdownAffectCrew)AND((vehicle _man)!=_man))exitWith{};
_man setUnconscious TRUE;
sleep 1;
sleep(dmpKnockdownDuration call BIS_fnc_randomNum);
_man setUnconscious FALSE;
//_man doMove [1,1];sleep 5;_man doMove(getPos _man);