private["_man","_chat","_dialog","_list","_dialogOptions"];
_man=_this select 0;
dmpCurrentTalker=_man;
if!(alive _man)exitWith{};
if(_man getVariable"dmpPOW")exitWith{[_man]execVM"DMP\Scripts\Interaction\InteractSoldier.sqf"};
if(dialog)then{closeDialog 0};
sleep .2;
if(!dialog)then{createDialog"dmp_DialogInteraction"};
_man forceSpeed 0;
_man lookAt getPos player;
_man lookAt player;
((findDisplay 7000)displayCtrl 7000)ctrlSetText format["%1 (%2)",name _man,side _man];
_chat="";
//((findDisplay 7000)displayCtrl 7001)ctrlSetStructuredText parseText format["""%1""",_chat];
{ctrlEnable[_x,TRUE]}forEach[7010];
_dialog=findDisplay 7000;
_list=_dialog displayCtrl 7010;
lbClear _list;
_dialogOptions=[];
_dialogOptions=[]+dmpInteractionCiv;
{_list lbAdd(_x select 0);_list lbSetData[(lbSize _list)-1,(_x select 1)]}forEach _dialogOptions;