private["_group","_targetPos","_pos","_array","_cswType","_csw","_road","_dir","_success","_cswTypes"];
_group=_this select 0;
_targetPos=_this select 1;
_cswTypes=_this select 2;
//_group setVariable["Vcm_Disable",true];
_pos=getPos(leader _group);
_cswType=selectRandom _cswTypes;
_csw=createVehicle[_cswType,_pos,[],0,"NONE"];
sleep 1;
_dir=[_csw,_targetPos]call BIS_fnc_dirTo;
_csw setDir _dir;
_csw setPos(getPos _csw);
_group setFormDir _dir;
(leader _group)assignAsGunner _csw;
(leader _group)moveInGunner _csw;
_group setCombatMode"YELLOW";
_group setBehaviour"COMBAT";
_csw setVariable["dmpAItype","Static",TRUE];