private["_group","_pos"];
if(isNil{(_this select 0)})exitWith{};
_group=_this select 0;
_pos=_this select 1;
if((random 10)>5)exitWith{_group execVM"DMP\Scripts\AI\EnhancedPatrol.sqf"};
_group setCombatMode"RED";
_group setBehaviour"SAFE";
_group setFormation"FILE";
{deleteWaypoint _x}forEach(waypoints _group);
sleep 1;
_group addWaypoint[_pos,0];
_group addWaypoint[_pos,1];
sleep 1;
{_x setWaypointType"GUARD"}forEach(waypoints _group);