private["_module","_types"];
_module=_this;
_types=[];
if((_module getVariable"dmpLocationTypeAirport")=="TRUE")then{_types pushBack"Airport"};
if((_module getVariable"dmpLocationTypeArea")=="TRUE")then{_types pushBack"Area"};
if((_module getVariable"dmpLocationTypeBorderCrossing")=="TRUE")then{_types pushBack"BorderCrossing"};
if((_module getVariable"dmpLocationTypeCityCenter")=="TRUE")then{_types pushBack"CityCenter"};
if((_module getVariable"dmpLocationTypeCivilDefense")=="TRUE")then{_types pushBack"CivilDefense"};
if((_module getVariable"dmpLocationTypeCulturalProperty")=="TRUE")then{_types pushBack"CulturalProperty"};
if((_module getVariable"dmpLocationTypeDangerousForces")=="TRUE")then{_types pushBack"DangerousForces"};
if((_module getVariable"dmpLocationTypeFlag")=="TRUE")then{_types pushBack"Flag"};
if((_module getVariable"dmpLocationTypeFlatArea")=="TRUE")then{_types pushBack"FlatArea"};
if((_module getVariable"dmpLocationTypeFlatAreaCity")=="TRUE")then{_types pushBack"FlatAreaCity"};
if((_module getVariable"dmpLocationTypeFlatAreaCitySmall")=="TRUE")then{_types pushBack"FlatAreaCitySmall"};
if((_module getVariable"dmpLocationTypeHill")=="TRUE")then{_types pushBack"Hill"};
if((_module getVariable"dmpLocationTypeHistoricalSite")=="TRUE")then{_types pushBack"HistoricalSite"};
if((_module getVariable"dmpLocationTypeInvisible")=="TRUE")then{_types pushBack"Invisible"};
if((_module getVariable"dmpLocationTypeMount")=="TRUE")then{_types pushBack"Mount"};
if((_module getVariable"dmpLocationTypeName")=="TRUE")then{_types pushBack"Name"};
if((_module getVariable"dmpLocationTypeNameCity")=="TRUE")then{_types pushBack"NameCity"};
if((_module getVariable"dmpLocationTypeNameCityCapital")=="TRUE")then{_types pushBack"NameCityCapital"};
if((_module getVariable"dmpLocationTypeNameLocal")=="TRUE")then{_types pushBack"NameLocal"};
if((_module getVariable"dmpLocationTypeNameMarine")=="TRUE")then{_types pushBack"NameMarine"};
if((_module getVariable"dmpLocationTypeNameVillage")=="TRUE")then{_types pushBack"NameVillage"};
if((_module getVariable"dmpLocationTypeRockArea")=="TRUE")then{_types pushBack"RockArea"};
if((_module getVariable"dmpLocationTypeSafetyZone")=="TRUE")then{_types pushBack"SafetyZone"};
if((_module getVariable"dmpLocationTypeStrategic")=="TRUE")then{_types pushBack"Strategic"};
if((_module getVariable"dmpLocationTypeStrongpointArea")=="TRUE")then{_types pushBack"StrongpointArea"};
if((_module getVariable"dmpLocationTypeVegetationBroadleaf")=="TRUE")then{_types pushBack"VegetationBroadleaf"};
if((_module getVariable"dmpLocationTypeVegetationFir")=="TRUE")then{_types pushBack"VegetationFir"};
if((_module getVariable"dmpLocationTypeVegetationPalm")=="TRUE")then{_types pushBack"VegetationPalm"};
if((_module getVariable"dmpLocationTypeVegetationVineyard")=="TRUE")then{_types pushBack"VegetationVineyard"};
if((_module getVariable"dmpLocationTypeViewPoint")=="TRUE")then{_types pushBack"ViewPoint"};
waitUntil{!(isNil"dmpLocationTypes")};
sleep 1;
dmpLocationTypes=_types;