private["_dialog","_list","_sleepArray"];
closeDialog 0;
sleep .3;
if(!dialog)then{createDialog"dmpDialogSleep"};
sleep .2;
ctrlShow[11000,TRUE];
_dialog=findDisplay 11000;
_sleepArray=call dmp_fnc_PreSleepCheck;
if(_sleepArray select 0)then{((findDisplay 11000)displayCtrl 11001)ctrlSetText"Inside"};
if(_sleepArray select 1)then{((findDisplay 11000)displayCtrl 11002)ctrlSetText"Using tent"};
if(_sleepArray select 2)then{((findDisplay 11000)displayCtrl 11003)ctrlSetText"Using bed/sleeping bag"};