private["_locations","_buildings","_radius","_i","_c"];
if!(isServer)exitWith{};
if(dmpDebug)then{systemChat"Starting loot placement"};
_locations=[];
_buildings=[];
_radius=500;
_radius=dmpRemoteSize;
_i=1;
_c=0;
{_locations pushBack _x}forEach dmpLocations;
{_locations pushBack _x}forEach dmpRemoteAreas;
//{_locations pushBack _x}forEach dmpCompounds;
_c=count _locations;
{
_buildings=_x nearObjects["House",_radius];
//{_x call dmp_fnc_AddBuilding;sleep .001}forEach _buildings;
{_x call dmp_fnc_AddBuilding}forEach _buildings;
//sleep dmpLootSleep;
if(dmpDebug)then{systemChat format["Loot: %1 / %2",_i,_c];_i=_i+1};
}forEach _locations;
dmpLootReady=TRUE;
if(dmpDebug)then{systemChat"Loot placement DONE"};