private["_admin"];
dmpAdminSide=WEST;
dmpAdminGroup=grpNull;
_admin=FALSE;
if((call BIS_fnc_admin)>0)then{_admin=TRUE};
if(isServer)then{_admin=TRUE};
if(dmpAdmin)then{_admin=TRUE};
if!(_admin)exitWith{hintSilent"Not an admin"};
if(dialog)then{closeDialog 0};
sleep .3;
execVM"DMP\Scripts\Admin\ShowDialog.sqf";
sleep .5;
dmpAntiSpam=FALSE;