private["_item","_type"];
_item=_this;
_type="ITEM";
if(isClass(configFile>>"cfgMagazines">>_x))then{_type="MAGAZINE"};
if(isClass(configFile>>"cfgWeapons">>_x))then{
	if((getNumber(configFile>>"cfgWeapons">>_x>>"type"))in[1,2,4])exitWith{_type="WEAPON"};
	_type="ITEM";
};
if(isClass(configFile>>"cfgVehicles">>_x))then{
	if(getNumber(configFile>>"cfgVehicles">>_x>>"isbackpack")==1)exitWith{_type="BACKPACK"};
};
if(isClass(configFile>>"cfgGlasses">>_x))then{_type="ITEM"};
_type