//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 210.149954 on Stable branch
// Generated with ALiVE version 1.17.0.2209061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_Serbia {
        displayName = "Serbia";
        side = 1;
        flag = "\rhssaf\addons\rhssaf_main\data\flags\flag_serbia_co.paa";
        icon = "\rhssaf\addons\rhssaf_main\data\icons\factions\rhssaf_faction_army_co.paa";
        priority = -9;
    };
};