if!(isServer)exitWith{};
private["_r","_f","_o","_w"];
_r=random 1;
_f=random 1;
_o=random 1;
_w=random 360;
[0,_r]remoteExec["setRain"];
[0,_f]remoteExec["setFog"];
[0,_o]remoteExec["setOvercast"];
[0,_w]remoteExec["setWindDir"];