private["_pos","_side","_activationDistance","_bomberTypes","_power","_bombType","_group","_bomber","_c","_bomb","_triggerDistance","_targets","_b","_explode","_sleep","_bomb1","_bomb2","_bomb3","_yell","_yellChance"];
_pos=_this select 0;
_side=_this select 1;
_activationDistance=_this select 2;
_triggerDistance=_this select 3;
_bomberTypes=_this select 4;
_power=_this select 5;
_yellChance=_this select 6;
_yell=_this select 7;
_bombType="M_Mo_82mm_AT";
if(_power=="HUGE")then{_bombType="Bomb_03_F"};
_bomber=objNull;
_group=grpNull;
_buildings=[];
_building=objNull;
_positions=[];
if((count _this)>8)then{_bomber=_this select 8;_group=group _bomber}else{
	_group=createGroup _side;
	(selectRandom _bomberTypes)createunit[_pos,_group,"",1,"COLONEL"];
	sleep 1;
	_bomber=(units _group)select 0;
	_buildings=nearestObjects[_bomber,["HOUSE"],200];
	{_positions=[_x]call BIS_fnc_buildingPositions;if((count _positions)<1)then{_buildings=_buildings-[_x]}}ForEach _buildings;
	if((count _buildings)>0)then{
		_building=selectRandom _buildings;
		_positions=[_building]call BIS_fnc_buildingPositions;
		_pos=selectRandom _positions;
		_pos=[_pos select 0,_pos select 1,(_pos select 2)+1];
		_bomber setVehiclePosition[_pos,[],0,"NONE"];
	};
};
{_x allowFleeing 0;_x disableAI"SUPPRESSION";_x disableAI"COVER";_x disableAI"AUTOCOMBAT";_x disableAI"MINEDETECTION"}forEach units _group;
_group setCombatMode"BLUE";
_group setBehaviour"CARELESS";
_group setSpeedMode"FULL";
_bomber setUnitPos"UP";
_bomber addVest"V_TacChestrig_cbr_F";
_bomb1="DemoCharge_Remote_Ammo"createVehicle(getPos _bomber); 
_bomb1 attachTo[_bomber,[-0.1,0.1,0.15],"Pelvis"]; 
_bomb1 setVectorDirAndUp[[0.5,0.5,0],[-0.5,0.5,0]]; 
_bomb2="DemoCharge_Remote_Ammo"createVehicle(getPos _bomber);
_bomb2 attachTo[_bomber,[0,0.15,0.15],"Pelvis"]; 
_bomb2 setVectorDirAndUp[[1,0,0],[0,1,0]]; 
_bomb3="DemoCharge_Remote_Ammo"createVehicle(getPos _bomber); 
_bomb3 attachTo[_bomber,[0.1,0.1,0.15],"Pelvis"]; 
_bomb3 setVectorDirAndUp[[0.5,-0.5,0],[0.5,0.5,0]]; 
_bomber setSkill 1;
_bomber setVariable["dmpAItype","SuicideBomber",TRUE];
if(dmpDebug)then{[_group,"SuicideBomber"]execVM"DMP\Scripts\AI\Track.sqf"};
_bomber allowFleeing 0;
_bomber setSkill["spotDistance",1];
_bomber setSkill["spotTime",1];
_targets=[];
_b=objNull;
_explode=TRUE;
_sleep=2;
_doYell=FALSE;
if((random 100)<=_yellChance)then{_doYell=TRUE};
while{TRUE}do{
	if!(alive _bomber)exitWith{};
	_targets=_bomber targets[TRUE,_activationDistance];
	if((count _targets)>0)then{
		if(_doYell)then{_bomber say3D _yell;_doYell=FALSE};
		_targets=[_targets,[],{(getPos _bomber)distance _x},"ASCEND"]call BIS_fnc_SortBy;
		if(((_targets select 0)distance _bomber)<_triggerDistance)exitWith{_sleep=-1};
		_bomber move(getPos(_targets select 0));
		_sleep=2;
	};
	if(_sleep<0)exitWith{};
	sleep _sleep;
	_sleep=2;
};
if(_explode)then{_b=_bombType createVehicle(getPos _bomber);deleteVehicle _bomber;_b setDammage 1;{deleteVehicle _x}forEach[_bomb1,_bomb2,_bomb3]};